name: f95france-dashboard

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: f96-trad-dash-app
    restart: unless-stopped

    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000

    ports:
      - '${APP_PORT:-3000}:3000'

    networks:
      - coolify

networks:
  coolify:
    external: true
