filebeat.inputs:
  - type: filestream
    id: f95france-dashboard-jsonl
    enabled: true

    paths:
      - /app/logs/*.log

    parsers:
      - ndjson:
          target: ''
          overwrite_keys: true
          add_error_key: true

processors:
  - add_host_metadata: ~

# Custom Index
setup.ilm.enabled: false

setup.template.name: 'f95france-dashboard'
setup.template.pattern: 'f95france-dashboard-*'
setup.template.overwrite: true

output.elasticsearch:
  hosts: ['${ELASTICSEARCH_HOST}']
  username: '${ELASTICSEARCH_USERNAME}'
  password: '${ELASTICSEARCH_PASSWORD}'
  index: 'f95france-dashboard-%{+yyyy.MM.dd}'

setup.kibana:
  host: '${KIBANA_HOST}'
