filebeat.inputs:
  - type: filestream
    id: f95france-dashboard-jsonl
    enabled: true

    paths:
      - /app/logs/*.log

    parsers:
      - ndjson:
          target: ''
          overwrite_keys: true
          add_error_key: true

processors:
  - add_host_metadata: ~

setup.ilm.enabled: false
setup.template.enabled: false

output.elasticsearch:
  hosts: ['${ELASTICSEARCH_HOST}']
  username: '${ELASTICSEARCH_USERNAME}'
  password: '${ELASTICSEARCH_PASSWORD}'
  index: 'f95france-dashboard-%{+yyyy.MM.dd}'
