[phases.setup]
nixPkgs = ["nodejs_24", "bun"]

[phases.install]
cmds = [
  "bun install --frozen-lockfile"
]

[phases.build]
cmds = ["bun run build", "bun install --frozen-lockfile --production"]

[start]
cmd = "node build/handler.js"
